
package com.swift.gpi.tracker.g4csdk.example;

import static java.util.Arrays.asList;

import java.util.List;

import org.junit.Ignore;
import org.junit.Test;

import com.swift.gpi.tracker.g4csdk.ApiException;
import com.swift.gpi.tracker.g4csdk.api.SearchingForCorporatePaymentTransactionsApi;
import com.swift.gpi.tracker.g4csdk.model.CamtA0800101;
import com.swift.gpi.tracker.g4csdk.model.CamtA0800201;
import com.swift.gpi.tracker.g4csdk.model.DateTimePeriodDetails;
import com.swift.gpi.tracker.g4csdk.model.GetCorporatePaymentTransactionsRequest;



/**
 * API tests for SearchingForCorporatePaymentTransactionsApi
 */
@Ignore
public class SearchingForCorporatePaymentTransactionsApiTest {

	@Test
    public void getCorporatePaymentTransactionsPostTest() throws ApiException {
    	SearchingForCorporatePaymentTransactionsApi apiInstance = new SearchingForCorporatePaymentTransactionsApi();
        String laUApplicationID = "001"; // String | ID that identifies the application generationg the API and used by the gpi Connector to retrieve the related LAU keys
        String laUVersion = "1.0"; // String | version of the LAUSigned header. Mandatory. \"1.0\" for this first release
        String laUCallTime = "2018-03-23T15:56:26.728Z"; // String | timestamp in UTC of the API call in the format YYYY-MM-DDTHH:MM:SS.sssZ
        String laURequestNonce = "e802ab96-bb3a-4965-9139-5214b9f0f074"; // String | a random value generated by the client. Provided with the request and copied by the gpi Connector on the response
        String laUSigned = "(ApplAPIKey=yVGhKiV5z1ZGdaqFXoZ8AiSA9n5CrY6B),(RBACRole=[FullViewer/Scope/cclabeb0])"; // String | service specific HTTP headers
        String laUSignature = "U1khA8h9Lm1PqzB99fG6uw=="; // String | contains the LAU signature, base64 ecoded
        String xApiKey = "yVGhKiV5z1ZGdaqFXoZ8AiSA9n5CrY6B"; // String | An API key given to your application to authenticate against the sandbox URL
        CamtA0800101 requestBody = new CamtA0800101();// CamtA0800101 | Contains the request to obtain information on the corporate status of one or more payment transaction
        requestBody.setGetCorporatePaymentTransactionsRequest(new GetCorporatePaymentTransactionsRequest());
        List<String> myInstitution = asList("BANABEBBXXX");
        requestBody.getGetCorporatePaymentTransactionsRequest().setMyInstitution(myInstitution);
        requestBody.getGetCorporatePaymentTransactionsRequest().setTimeWindow(new DateTimePeriodDetails());
        requestBody.getGetCorporatePaymentTransactionsRequest().setMaximumNumber("10");
        requestBody.getGetCorporatePaymentTransactionsRequest().setMore("more");
        requestBody.getGetCorporatePaymentTransactionsRequest().setUetr("eb6305c9-1f7f-49de-aed0-16487c27b42d");
		String xRecord = "1"; // String | A type of API response to get from API Sandbox. A value between 1 and 7
        try {
            CamtA0800201 result = apiInstance.getCorporatePaymentTransactionsPost(laUApplicationID, laUVersion, laUCallTime, laURequestNonce, laUSigned, laUSignature, xApiKey, requestBody, xRecord);
            System.out.println(result);
        } catch (ApiException e) {
            System.err.println("Exception when calling SearchingForCorporatePaymentTransactionsApi#getCorporatePaymentTransactionsPost");
            e.printStackTrace();
        }
    }
    
}
